//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_51172
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// BSForBuildings.
    /// </summary>
    // *** Start programmer edit section *** (BSForBuildings CustomAttributes)

    // *** End programmer edit section *** (BSForBuildings CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class BSForBuildings : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (BSForBuildings CustomMembers)

        // *** End programmer edit section *** (BSForBuildings CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateBuildings CustomAttributes)

        // *** End programmer edit section *** (OnUpdateBuildings CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateBuildings(IIS.Product_51172.Buildings UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateBuildings)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateBuildings)
        }
    }
}
