//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_51172
{
    
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// BSForSectionNets.
    /// </summary>
    // *** Start programmer edit section *** (BSForSectionNets CustomAttributes)

    // *** End programmer edit section *** (BSForSectionNets CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class BSForSectionNets : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (BSForSectionNets CustomMembers)

        // *** End programmer edit section *** (BSForSectionNets CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateSectionNets CustomAttributes)

        // *** End programmer edit section *** (OnUpdateSectionNets CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateSectionNets(IIS.Product_51172.SectionNets UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateSectionNets)
            if (UpdatedObject.GetStatus() == ObjectStatus.Created || UpdatedObject.GetStatus() == ObjectStatus.Altered)
            {
                if (Array.IndexOf(UpdatedObject.GetAlteredPropertyNames(), "NumerSectionNet") >= 0)
                {
                    string NameSN = "";
                    if (!SectionNets.CheckUnNumer(UpdatedObject.NumerSectionNet, ref NameSN))
                    {
                        string errStr = $"Данный номер уже присвоен другому(-им) участку(-ам) сети: "+Environment.NewLine+NameSN;
                        throw new Exception(errStr);
                    }
                }
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateSectionNets)
        }
    }
}
