//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_51172
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CheckForUniqueness.
    /// </summary>
    // *** Start programmer edit section *** (CheckForUniqueness CustomAttributes)

    // *** End programmer edit section *** (CheckForUniqueness CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CheckForUniqueness : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (CheckForUniqueness CustomMembers)

        // *** End programmer edit section *** (CheckForUniqueness CustomMembers)

    }
}
