//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_51172
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Clients CustomAttributes)

    // *** End programmer edit section *** (Clients CustomAttributes)
    [AutoAltered()]
    [Caption("Клиенты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ClientsE", new string[] {
            "FIO as \'ФИО клиента\'",
            "account as \'Лицевой счет\'"})]
    [View("ClientsL", new string[] {
            "FIO as \'ФИО клиента\'",
            "account as \'Лицевой счет\'"})]
    public class Clients : ICSSoft.STORMNET.DataObject
    {
        
        private string fFIO;
        
        private int faccount;
        
        // *** Start programmer edit section *** (Clients CustomMembers)

        // *** End programmer edit section *** (Clients CustomMembers)

        
        /// <summary>
        /// FIO.
        /// </summary>
        // *** Start programmer edit section *** (Clients.FIO CustomAttributes)

        // *** End programmer edit section *** (Clients.FIO CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string FIO
        {
            get
            {
                // *** Start programmer edit section *** (Clients.FIO Get start)

                // *** End programmer edit section *** (Clients.FIO Get start)
                string result = this.fFIO;
                // *** Start programmer edit section *** (Clients.FIO Get end)

                // *** End programmer edit section *** (Clients.FIO Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Clients.FIO Set start)

                // *** End programmer edit section *** (Clients.FIO Set start)
                this.fFIO = value;
                // *** Start programmer edit section *** (Clients.FIO Set end)

                // *** End programmer edit section *** (Clients.FIO Set end)
            }
        }
        
        /// <summary>
        /// account.
        /// </summary>
        // *** Start programmer edit section *** (Clients.account CustomAttributes)

        // *** End programmer edit section *** (Clients.account CustomAttributes)
        [NotNull()]
        public virtual int account
        {
            get
            {
                // *** Start programmer edit section *** (Clients.account Get start)

                // *** End programmer edit section *** (Clients.account Get start)
                int result = this.faccount;
                // *** Start programmer edit section *** (Clients.account Get end)

                // *** End programmer edit section *** (Clients.account Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Clients.account Set start)

                // *** End programmer edit section *** (Clients.account Set start)
                this.faccount = value;
                // *** Start programmer edit section *** (Clients.account Set end)

                // *** End programmer edit section *** (Clients.account Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ClientsE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClientsE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClientsE", typeof(IIS.Product_51172.Clients));
                }
            }
            
            /// <summary>
            /// "ClientsL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClientsL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClientsL", typeof(IIS.Product_51172.Clients));
                }
            }
        }
    }
}
