//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_51172
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Микрорайоны.
    /// </summary>
    // *** Start programmer edit section *** (Microdistrict CustomAttributes)

    // *** End programmer edit section *** (Microdistrict CustomAttributes)
    [AutoAltered()]
    [Caption("Микрорайоны")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MicrodistrictE", new string[] {
            "NameMicrodistrict as \'Названия микрорайона\'"})]
    [View("MicrodistrictL", new string[] {
            "NameMicrodistrict as \'Названия микрорайона\'"})]
    public class Microdistrict : ICSSoft.STORMNET.DataObject
    {
        
        private string fNameMicrodistrict;
        
        // *** Start programmer edit section *** (Microdistrict CustomMembers)

        // *** End programmer edit section *** (Microdistrict CustomMembers)

        
        /// <summary>
        /// NameMicrodistrict.
        /// </summary>
        // *** Start programmer edit section *** (Microdistrict.NameMicrodistrict CustomAttributes)

        // *** End programmer edit section *** (Microdistrict.NameMicrodistrict CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string NameMicrodistrict
        {
            get
            {
                // *** Start programmer edit section *** (Microdistrict.NameMicrodistrict Get start)

                // *** End programmer edit section *** (Microdistrict.NameMicrodistrict Get start)
                string result = this.fNameMicrodistrict;
                // *** Start programmer edit section *** (Microdistrict.NameMicrodistrict Get end)

                // *** End programmer edit section *** (Microdistrict.NameMicrodistrict Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Microdistrict.NameMicrodistrict Set start)

                // *** End programmer edit section *** (Microdistrict.NameMicrodistrict Set start)
                this.fNameMicrodistrict = value;
                // *** Start programmer edit section *** (Microdistrict.NameMicrodistrict Set end)

                // *** End programmer edit section *** (Microdistrict.NameMicrodistrict Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MicrodistrictE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MicrodistrictE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MicrodistrictE", typeof(IIS.Product_51172.Microdistrict));
                }
            }
            
            /// <summary>
            /// "MicrodistrictL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MicrodistrictL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MicrodistrictL", typeof(IIS.Product_51172.Microdistrict));
                }
            }
        }
    }
}
