//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_51172
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Объект теплопотребления.
    /// </summary>
    // *** Start programmer edit section *** (ObjectsHeat CustomAttributes)

    // *** End programmer edit section *** (ObjectsHeat CustomAttributes)
    [BusinessServer("IIS.Product_51172.UseDllCodeDecode, Product_51172.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Объект теплопотребления")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ObjectsHeatE", new string[] {
            "NameObjectsHeat as \'Название объекта теплопотребления\'",
            "DateReg as \'Дата регистрации\'",
            "Area as \'Площадь объекта\'",
            "QRcode as \'Расшифровка QR-code\'",
            "Buildings as \'Адрес здания\'",
            "Buildings.NameBuildings as \'Адрес здания\'",
            "Clients as \'ФИО клиента\'",
            "Clients.FIO as \'ФИО клиента\'"}, Hidden=new string[] {
            "QRcode",
            "Buildings.NameBuildings",
            "Clients.FIO"})]
    [MasterViewDefineAttribute("ObjectsHeatE", "Buildings", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "NameBuildings")]
    [MasterViewDefineAttribute("ObjectsHeatE", "Clients", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FIO")]
    [View("ObjectsHeatL", new string[] {
            "NameObjectsHeat as \'Название объекта теплопотребления\'",
            "DateReg as \'Дата регистрации\'",
            "Area as \'Площадь объекта\'",
            "QRcode as \'Расшифровка QR-code\'",
            "Buildings.NameBuildings as \'Адрес здания\'",
            "Clients.FIO as \'ФИО клиента\'"}, Hidden=new string[] {
            "QRcode"})]
    public class ObjectsHeat : ICSSoft.STORMNET.DataObject
    {
        
        private string fNameObjectsHeat;
        
        private System.DateTime fDateReg;
        
        private string fQRcode;
        
        private double fArea;
        
        private IIS.Product_51172.Buildings fBuildings;
        
        private IIS.Product_51172.Clients fClients;
        
        private IIS.Product_51172.DetailArrayOfSectionNets fSectionNets;
        
        // *** Start programmer edit section *** (ObjectsHeat CustomMembers)

        // *** End programmer edit section *** (ObjectsHeat CustomMembers)

        
        /// <summary>
        /// NameObjectsHeat.
        /// </summary>
        // *** Start programmer edit section *** (ObjectsHeat.NameObjectsHeat CustomAttributes)

        // *** End programmer edit section *** (ObjectsHeat.NameObjectsHeat CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string NameObjectsHeat
        {
            get
            {
                // *** Start programmer edit section *** (ObjectsHeat.NameObjectsHeat Get start)

                // *** End programmer edit section *** (ObjectsHeat.NameObjectsHeat Get start)
                string result = this.fNameObjectsHeat;
                // *** Start programmer edit section *** (ObjectsHeat.NameObjectsHeat Get end)

                // *** End programmer edit section *** (ObjectsHeat.NameObjectsHeat Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ObjectsHeat.NameObjectsHeat Set start)

                // *** End programmer edit section *** (ObjectsHeat.NameObjectsHeat Set start)
                this.fNameObjectsHeat = value;
                // *** Start programmer edit section *** (ObjectsHeat.NameObjectsHeat Set end)

                // *** End programmer edit section *** (ObjectsHeat.NameObjectsHeat Set end)
            }
        }
        
        /// <summary>
        /// DateReg.
        /// </summary>
        // *** Start programmer edit section *** (ObjectsHeat.DateReg CustomAttributes)

        // *** End programmer edit section *** (ObjectsHeat.DateReg CustomAttributes)
        public virtual System.DateTime DateReg
        {
            get
            {
                // *** Start programmer edit section *** (ObjectsHeat.DateReg Get start)

                // *** End programmer edit section *** (ObjectsHeat.DateReg Get start)
                System.DateTime result = this.fDateReg;
                // *** Start programmer edit section *** (ObjectsHeat.DateReg Get end)

                // *** End programmer edit section *** (ObjectsHeat.DateReg Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ObjectsHeat.DateReg Set start)

                // *** End programmer edit section *** (ObjectsHeat.DateReg Set start)
                this.fDateReg = value;
                // *** Start programmer edit section *** (ObjectsHeat.DateReg Set end)

                // *** End programmer edit section *** (ObjectsHeat.DateReg Set end)
            }
        }
        
        /// <summary>
        /// QRcode.
        /// </summary>
        // *** Start programmer edit section *** (ObjectsHeat.QRcode CustomAttributes)

        // *** End programmer edit section *** (ObjectsHeat.QRcode CustomAttributes)
        [StrLen(255)]
        public virtual string QRcode
        {
            get
            {
                // *** Start programmer edit section *** (ObjectsHeat.QRcode Get start)

                // *** End programmer edit section *** (ObjectsHeat.QRcode Get start)
                string result = this.fQRcode;
                // *** Start programmer edit section *** (ObjectsHeat.QRcode Get end)

                // *** End programmer edit section *** (ObjectsHeat.QRcode Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ObjectsHeat.QRcode Set start)

                // *** End programmer edit section *** (ObjectsHeat.QRcode Set start)
                this.fQRcode = value;
                // *** Start programmer edit section *** (ObjectsHeat.QRcode Set end)

                // *** End programmer edit section *** (ObjectsHeat.QRcode Set end)
            }
        }
        
        /// <summary>
        /// Area.
        /// </summary>
        // *** Start programmer edit section *** (ObjectsHeat.Area CustomAttributes)

        // *** End programmer edit section *** (ObjectsHeat.Area CustomAttributes)
        public virtual double Area
        {
            get
            {
                // *** Start programmer edit section *** (ObjectsHeat.Area Get start)

                // *** End programmer edit section *** (ObjectsHeat.Area Get start)
                double result = this.fArea;
                // *** Start programmer edit section *** (ObjectsHeat.Area Get end)

                // *** End programmer edit section *** (ObjectsHeat.Area Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ObjectsHeat.Area Set start)

                // *** End programmer edit section *** (ObjectsHeat.Area Set start)
                this.fArea = value;
                // *** Start programmer edit section *** (ObjectsHeat.Area Set end)

                // *** End programmer edit section *** (ObjectsHeat.Area Set end)
            }
        }
        
        /// <summary>
        /// Объект теплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ObjectsHeat.Buildings CustomAttributes)

        // *** End programmer edit section *** (ObjectsHeat.Buildings CustomAttributes)
        [PropertyStorage(new string[] {
                "Buildings"})]
        [NotNull()]
        public virtual IIS.Product_51172.Buildings Buildings
        {
            get
            {
                // *** Start programmer edit section *** (ObjectsHeat.Buildings Get start)

                // *** End programmer edit section *** (ObjectsHeat.Buildings Get start)
                IIS.Product_51172.Buildings result = this.fBuildings;
                // *** Start programmer edit section *** (ObjectsHeat.Buildings Get end)

                // *** End programmer edit section *** (ObjectsHeat.Buildings Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ObjectsHeat.Buildings Set start)

                // *** End programmer edit section *** (ObjectsHeat.Buildings Set start)
                this.fBuildings = value;
                // *** Start programmer edit section *** (ObjectsHeat.Buildings Set end)

                // *** End programmer edit section *** (ObjectsHeat.Buildings Set end)
            }
        }
        
        /// <summary>
        /// Объект теплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ObjectsHeat.Clients CustomAttributes)

        // *** End programmer edit section *** (ObjectsHeat.Clients CustomAttributes)
        [PropertyStorage(new string[] {
                "Clients"})]
        [NotNull()]
        public virtual IIS.Product_51172.Clients Clients
        {
            get
            {
                // *** Start programmer edit section *** (ObjectsHeat.Clients Get start)

                // *** End programmer edit section *** (ObjectsHeat.Clients Get start)
                IIS.Product_51172.Clients result = this.fClients;
                // *** Start programmer edit section *** (ObjectsHeat.Clients Get end)

                // *** End programmer edit section *** (ObjectsHeat.Clients Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ObjectsHeat.Clients Set start)

                // *** End programmer edit section *** (ObjectsHeat.Clients Set start)
                this.fClients = value;
                // *** Start programmer edit section *** (ObjectsHeat.Clients Set end)

                // *** End programmer edit section *** (ObjectsHeat.Clients Set end)
            }
        }
        
        /// <summary>
        /// Объект теплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ObjectsHeat.SectionNets CustomAttributes)

        // *** End programmer edit section *** (ObjectsHeat.SectionNets CustomAttributes)
        public virtual IIS.Product_51172.DetailArrayOfSectionNets SectionNets
        {
            get
            {
                // *** Start programmer edit section *** (ObjectsHeat.SectionNets Get start)

                // *** End programmer edit section *** (ObjectsHeat.SectionNets Get start)
                if ((this.fSectionNets == null))
                {
                    this.fSectionNets = new IIS.Product_51172.DetailArrayOfSectionNets(this);
                }
                IIS.Product_51172.DetailArrayOfSectionNets result = this.fSectionNets;
                // *** Start programmer edit section *** (ObjectsHeat.SectionNets Get end)

                // *** End programmer edit section *** (ObjectsHeat.SectionNets Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ObjectsHeat.SectionNets Set start)

                // *** End programmer edit section *** (ObjectsHeat.SectionNets Set start)
                this.fSectionNets = value;
                // *** Start programmer edit section *** (ObjectsHeat.SectionNets Set end)

                // *** End programmer edit section *** (ObjectsHeat.SectionNets Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ObjectsHeatE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ObjectsHeatE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ObjectsHeatE", typeof(IIS.Product_51172.ObjectsHeat));
                }
            }
            
            /// <summary>
            /// "ObjectsHeatL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ObjectsHeatL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ObjectsHeatL", typeof(IIS.Product_51172.ObjectsHeat));
                }
            }
        }
    }
}
