//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_51172
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Типы изоляции.
    /// </summary>
    // *** Start programmer edit section *** (TypesOfInsulation CustomAttributes)

    // *** End programmer edit section *** (TypesOfInsulation CustomAttributes)
    [AutoAltered()]
    [Caption("Типы изоляции")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TypesOfInsulationE", new string[] {
            "NameTypesOfInsulation as \'Название типа изоляции\'"})]
    [View("TypesOfInsulationL", new string[] {
            "NameTypesOfInsulation as \'Название типа изоляции\'"})]
    public class TypesOfInsulation : ICSSoft.STORMNET.DataObject
    {
        
        private string fNameTypesOfInsulation;
        
        // *** Start programmer edit section *** (TypesOfInsulation CustomMembers)

        // *** End programmer edit section *** (TypesOfInsulation CustomMembers)

        
        /// <summary>
        /// NameTypesOfInsulation.
        /// </summary>
        // *** Start programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation CustomAttributes)

        // *** End programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string NameTypesOfInsulation
        {
            get
            {
                // *** Start programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation Get start)

                // *** End programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation Get start)
                string result = this.fNameTypesOfInsulation;
                // *** Start programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation Get end)

                // *** End programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation Set start)

                // *** End programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation Set start)
                this.fNameTypesOfInsulation = value;
                // *** Start programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation Set end)

                // *** End programmer edit section *** (TypesOfInsulation.NameTypesOfInsulation Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TypesOfInsulationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TypesOfInsulationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TypesOfInsulationE", typeof(IIS.Product_51172.TypesOfInsulation));
                }
            }
            
            /// <summary>
            /// "TypesOfInsulationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TypesOfInsulationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TypesOfInsulationL", typeof(IIS.Product_51172.TypesOfInsulation));
                }
            }
        }
    }
}
