//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_51172
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Типы прокладки.
    /// </summary>
    // *** Start programmer edit section *** (TypesSectionNet CustomAttributes)

    // *** End programmer edit section *** (TypesSectionNet CustomAttributes)
    public enum TypesSectionNet
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypesSectionNet.Внутренняя CustomAttributes)

        // *** End programmer edit section *** (TypesSectionNet.Внутренняя CustomAttributes)
        Внутренняя,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypesSectionNet.Наружная CustomAttributes)

        // *** End programmer edit section *** (TypesSectionNet.Наружная CustomAttributes)
        Наружная,
    }
}
