<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="SectionNetsE.aspx.cs" Inherits="IIS.Product_51172.SectionNetsE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " +  Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.EditFormHeaderCssClass %>">Участки сети</h2>
        <div class="<%= Constants.FormToolbarCssClass  + " " +  Constants.EditFormToolbarCssClass + " " + Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlNameSectionNetLabel" runat="server" Text="Название участка сети" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlNameSectionNet" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlNameSectionNetRequiredFieldValidator" runat="server" ControlToValidate="ctrlNameSectionNet"
                            ErrorMessage="Не указано: NameSectionNet" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlNumerSectionNetLabel" runat="server" Text="Номер участка сети" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlNumerSectionNet" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlNumerSectionNetRequiredFieldValidator" runat="server" ControlToValidate="ctrlNumerSectionNet"
                            ErrorMessage="Не указано: NumerSectionNet" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlTypesOfInsulationLabel" runat="server" Text="Тип изоляции" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlTypesOfInsulation" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlTypesOfInsulationRequiredFieldValidator" runat="server" ControlToValidate="ctrlTypesOfInsulation"
                            ErrorMessage="Не указано: TypesOfInsulation" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlTypeSectionNetLabel" runat="server" Text="Тип прокладки сети" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlTypeSectionNet" CssClass="descTxt" runat="server">
	<asp:ListItem>Внутренняя</asp:ListItem>
<asp:ListItem>Наружная</asp:ListItem>

</asp:DropDownList>
<asp:RequiredFieldValidator ID="ctrlTypeSectionNetRequiredFieldValidator" runat="server" ControlToValidate="ctrlTypeSectionNet"
                            ErrorMessage="Не указано: TypeSectionNet" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlObjectsHeatLabel" runat="server" Text="Объект теплопотребления" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlObjectsHeat" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlObjectsHeatRequiredFieldValidator" runat="server" ControlToValidate="ctrlObjectsHeat"
                            ErrorMessage="Не указано: ObjectsHeat" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlStrOtherInformationsLabel" runat="server" Text="Информация" EnableViewState="False">
      
</asp:Label>
    <asp:TextBox CssClass="descTxt" ID="ctrlStrOtherInformations" runat="server" Width="400px" TextMode="MultiLine" ReadOnly="True"></asp:TextBox>

</div>
<div class="clearfix">

</div>
</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="FlexberryStyles">
    <style type="text/css">
        .descTxt {}
    </style>
</asp:Content>

