/*flexberryautogenerated="true"*/
namespace IIS.Product_51172
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class TypesOfInsulationL : BaseListForm<TypesOfInsulation>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public TypesOfInsulationL() : base(TypesOfInsulation.Views.TypesOfInsulationL)
        {
            EditPage = TypesOfInsulationE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/TypesOfInsulation/TypesOfInsulationL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
